---
elasticsearch_app_dir: "{{ COMMON_APP_DIR }}/elasticsearch"
elasticsearch_data_dir: "{{ COMMON_DATA_DIR }}/elasticsearch"
elasticsearch_log_dir: "{{ COMMON_LOG_DIR }}/elasticsearch"
elasticsearch_cfg_dir: "{{ COMMON_CFG_DIR }}/elasticsearch"
elasticsearch_version: "1.4.4"

elasticsearch_sha: "ec8b41c54a6d897479645b2507476e0824bc71db"
elasticsearch_url: "https://download.elasticsearch.org/elasticsearch/elasticsearch"
elasticsearch_user: "elasticsearch"
elasticsearch_group: "elasticsearch"


elasticsearch_file_rpm: "elasticsearch-{{ elasticsearch_version }}.noarch.rpm"
elasticsearch_file_deb: "elasticsearch-{{ elasticsearch_version }}.deb"

elasticsearch_home: /usr/share/elasticsearch
elasticsearch_bin: "{{ elasticsearch_home }}/bin/elasticsearch"

#
# Defaults for a single server installation.
ELASTICSEARCH_CLUSTERED: false
ELASTICSEARCH_HEAP_SIZE: "512m"
