---
KIBANA_SERVER_NAME: "{{ inventory_hostname }}"
KIBANA_NGINX_PORT: 80
KIBANA_SSL_NGINX_PORT: 443

kibana_app_dir: /edx/app/kibana
kibana_file: kibana-3.0.0.tar.gz
kibana_url: "https://download.elasticsearch.org/kibana/kibana/{{ kibana_file }}"
