- name: Ensure elasticsearch is enabled and started
  service: name=elasticsearch state=started enabled=yes

- name: Restart elastic when there has been an upgrade
  service: name=elasticsearch state=restarted enabled=yes
  when: elasticsearch_reinstall.changed
