---
LOGSTASH_DAYS_TO_KEEP: 30
LOGSTASH_ROTATE: true
logstash_app_dir: "{{ COMMON_APP_DIR }}/logstash"
logstash_log_dir: "{{ COMMON_LOG_DIR }}/logstash"
logstash_data_dir: "{{ COMMON_DATA_DIR }}/file_logs"
logstash_syslog_port: 514
logstash_file: logstash-1.4.2.tar.gz
logstash_url: "https://download.elasticsearch.org/logstash/logstash/"
logstash_python_requirements:
  - pyes
logstash_scripts_repo: https://github.com/crashdump/logstash-elasticsearch-scripts
logstash_rotate_cron:
  hour: 5
  minute: 42
logstash_optimize_cron:
  hour: 6
  minute: 15